name: Build

on: [ workflow_dispatch ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - run: |
      echo hello

  build-macos:
    runs-on: macos-latest
    steps:
    - run: echo Hello, MacOS!

  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - run: echo Hello, Linux!

  build-all:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
    - run: echo Hello, world!
