name: Build

on: [ workflow_dispatch ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: make clean all

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: make clean all

  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - run: sudo add-apt-repository ppa:deadsnakes/ppa
    - run: sudo apt-get install -y python3.9
    - run: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
    - uses: actions/checkout@v2
    - run: make clean all

  build-all:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
    - run: echo Hello, world!
