name: Build

on: [ workflow_dispatch ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: make clean all
    - uses: actions/upload-artifact@v2
      with:
        name: windows-lib
        path: pyxel/lib/windows/pyxel_wrapper.pyd

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: make clean all
    - uses: actions/upload-artifact@v2
      with:
        name: macos-lib
        path: pyxel/lib/macos/pyxel_wrapper.so

  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo add-apt-repository ppa:deadsnakes/ppa
    - run: sudo apt-get install -y python3.9 libsdl2-dev
    - run: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
    - run: make clean all
    - uses: actions/upload-artifact@v2
      with:
        name: linux-lib
        path: pyxel/lib/linux/pyxel_wrapper.so

  make-wheel:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
    - run: echo Hello, world!
    - uses: actions/download-artifact@v2
      with:
        name: windows-lib
        path: pyxel/lib/windows
    - uses: actions/download-artifact@v2
      with:
        name: macos-lib
        path: pyxel/lib/macos
    - uses: actions/download-artifact@v2
      with:
        name: linux-lib
        path: pyxel/lib/linux
    - run: ls pyxel/lib/windows
    - run: ls pyxel/lib/macos
    - run: ls pyxel/lib/linux
    - run: make wheel
