name: Build

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag'
      release-name:
        description: 'Release name'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: make clean all
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-windows-lib
        path: pyxel/lib/windows/*

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: make clean all
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-macos-lib
        path: pyxel/lib/macos/*

  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo add-apt-repository ppa:deadsnakes/ppa
    - run: sudo apt install -y python3.9 libsdl2-dev
    - run: sudo ln -nfs /usr/bin/python3.9 /usr/bin/python3
    - run: make clean all
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-linux-lib
        path: pyxel/lib/linux/*

  make-wheel:
    runs-on: macos-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-windows-lib
        path: pyxel/lib/windows
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-macos-lib
        path: pyxel/lib/macos
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-linux-lib
        path: pyxel/lib/linux
    - run: make wheel
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-wheel
        path: dist/*.whl

  package-windows:
    runs-on: windows-latest
    needs: make-wheel
    steps:
    - uses: actions/checkout@v2
    - run: choco install zip
    - run: pip install pyoxidizer
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-wheel
        path: dist
    - run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-windows-zip
        path: dist/*.zip
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-windows-exe
        path: dist/*.exe

  package-macos:
    runs-on: macos-latest
    needs: make-wheel
    steps:
    - uses: actions/checkout@v2
    - run: brew install pyoxidizer
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-wheel
        path: dist
    - run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-macos-zip
        path: dist/*.zip

  package-linux:
    runs-on: ubuntu-18.04
    needs: make-wheel
    steps:
    - uses: actions/checkout@v2
    - run: brew install pyoxidizer
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-wheel
        path: dist
    - run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: pyxel-linux-zip
        path: dist/*.zip

  release:
    runs_on: macos-latest
    needs: [package-windows, package-macos, package-linux]
    if: ${{ github.event.inputs.release-tag != '' && github.event.inputs.release_name != '' }}
    steps:
    - run: echo Release
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release-tag }}
        release_name: ${{ github.event.inputs.release-name }}
        draft: false
        prerelease: true
    #uses: actions/upload-release-asset@v1
    #env:
    #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #with:
    #  upload_url: ${{ steps.create_release.outputs.upload_url }}
    #  asset_path: ./src/artifacts/Linux.zip
    #  asset_name: go_linux_amd64.zip
    #  asset_content_type: application/zip
