name: Publish

on:
  release:
    types: published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - run: |
        VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        echo "{VERSION}={$VERSION}" >> $GITHUB_ENV
        echo "VERSION = $VERSION"

    #- uses: actions/checkout@v2
    #- name: Set up Python
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: '3.x'
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install setuptools wheel twine
    #- name: Build and publish
    #  env:
    #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #  run: twine upload dist/*.whl

    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: kitao/homebrew-pyxel
        event-type: update
        client-payload: '{"version": "${{ env.VERSION }}"}'
