name: Publish

on:
  release:
    types: published

jobs:
  publish-wheel:
    runs-on: ubuntu-latest
    steps:
    - run: |
        VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: kitao/homebrew-pyxel
        event-type: update
        client-payload: '{"version": "${{ env.VERSION }}"}'
    - run: |
        pip3 install twine
        wget https://github.com/kitao/pyxel/releases/download/v${{ env.VERSION }}/pyxel-${{ env.VERSION }}-py3-none-any.whl
        twine upload *.whl
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  publish-crates:
    runs-on: linux-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
        cd lib/engine
        cargo publish
        sleep 10
        cd ../wrapper
        cargo publish
