name: Publish

on:
  release:
    types: published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - run: |
        VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        echo "{VERSION}={$VERSION}" >> $GITHUB_ENV
        echo "VERSION = $VERSION"
