name: Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        required: true
        default: 'vX.X.X'
      release-name:
        type: string
        required: true
        default: 'Pyxel X.X.X'

jobs:
  call-build:
    uses: kitao/pyxel/.github/workflows/build.yml@main
    with:
      checkout-ref: ${{ github.event.inputs.checkout-ref }}

  create-release:
    runs-on: ubuntu-latest
    needs: call-build
    steps:
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release-tag }}
        release_name: ${{ github.event.inputs.release-name }}
        draft: true
        prerelease: true

  upload-files:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-wheel
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-windows-zip
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-windows-exe
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-macos-zip
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: pyxel-linux-zip
        path: dist
    - uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["dist/*"]'
