name: Trigger to build

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        type: string
        default: ''

jobs:
  call-workflow:
    uses: kitao/pyxel/.github/workflows/build.yml@main
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
